# fly.toml app configuration file generated for email-dev-praetoros-cloud on 2023-06-23T03:50:19+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "email-dev-praetoros-cloud"
primary_region = "syd"

[http_service]
  internal_port = 25
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
builder = "Dockerfile"
